### ISSUE TITLE
Doesnt work anymore

### ISSUE THREAD

**Issue by Birb236** [shadoxxhd/steamworkshopdownloader#1]
Doesnt work anymore just says ERROR! at downloading item

**Comment by Captchah** [comment]
If it says error, it probably means that the content you're trying to download cannot be downloaded anonymously, and you have to login with your Steam account/own the game to be able to download it. Strangely enough, I also got an exception on one of my downloads, which I'll post.

**Comment by XemorDio** [comment]
Unfortunately, he downloads mods for games that are available on the steam account. I personally have it.

**Comment by Captchah** [comment]
> Unfortunately, he downloads mods for games that are available on the steam account. I personally have it.

What do you mean? If you're facing an error, could you post the error message you're getting?

**Comment by XemorDio** [comment]
> 

`Steam Console Client (c) Valve Corporation - version 1653101151
-- type 'quit' to exit --
Loading Steam API...OK

Connecting anonymously to Steam Public...OK
Waiting for client config...OK
Waiting for user info...OK
Downloading item 1942446136 ...
ERROR! Download item 1942446136 failed (Failure).Redirecting stderr to 'D:\Games\Steam\steamcmd\logs\stderr.txt'
[  0%] РџСЂРѕРІРµСЂРєР° РЅР° РЅР°Р»РёС‡РёРµ РѕР±РЅРѕРІР»РµРЅРёР№...
[----] РџСЂРѕРІРµСЂРєР° СѓСЃС‚Р°РЅРѕРІРєРё...
`

**Comment by Captchah** [comment]
This issue is likely because the game does not allow anonymous downloads, and unfortunately it also seems to be game-locked (if you do not own the game on Steam, you can't download it).

**Comment by XemorDio** [comment]
> This issue is likely because the game does not allow anonymous downloads, and unfortunately from my tests (logging in anonymously and with my Steam account on SteamCMD) it also seems to be game-locked (if you do not own the game on Steam, you can't download it).

Okay, is there by any chance a list of games that allow anonymous downloading?

**Comment by aesthetictea** [comment]
xception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\iuser\AppData\Local\Programs\Python\Python310\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "C:\Users\user\AppData\Local\Temp\Temp1_steamworkshopdownloader-master.zip\steamworkshopdownloader-master\downloader.py", line 44, in download
    process = subprocess.Popen(args, stdout=subprocess.PIPE, errors='ignore')
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 966, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 1435, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

I got this error message. What do I do?

**Comment by shadoxxhd** [comment]
> > This issue is likely because the game does not allow anonymous downloads, and unfortunately from my tests (logging in anonymously and with my Steam account on SteamCMD) it also seems to be game-locked (if you do not own the game on Steam, you can't download it).
> 
> Okay, is there by any chance a list of games that allow anonymous downloading?

I'm not aware of such a list; since there are a lot of different workshops, creating and maintaining such a list manually would be ineffective anyway.
I may create an automatically generated list for this in the future.

**Comment by shadoxxhd** [comment]
@XemorDio Apparently, there is already a list of supported games for anonymous downloads: https://steamdb.info/sub/17906/apps/

(Source: https://www.reddit.com/r/swd_io/comments/vaf41f/comment/ic6oqnn/?utm_source=share&utm_medium=web2x&context=3)

**Comment by XemorDio** [comment]
> @XemorDio Apparently, there is already a list of supported games for anonymous downloads: https://steamdb.info/sub/17906/apps/
> 
> (Source: https://www.reddit.com/r/swd_io/comments/vaf41f/comment/ic6oqnn/?utm_source=share&utm_medium=web2x&context=3)

All games in the list or where there is no price? Thanks!

**Comment by RandDenner** [comment]
I believe it's all games in the list, as tit is a list of "**Anonymous** Dedicated Server Compatible" games.
(Apparently many more games would be on the list if the devs enabled just a setting or two on their Steam pages...)

**Comment by shadoxxhd** [comment]
> All games in the list or where there is no price? Thanks!

All games in the list should work.
