### ISSUE TITLE
Cities: Skylines support

### ISSUE THREAD

**Issue by KygekDev** [shadoxxhd/steamworkshopdownloader#10]
I've tried downloading an item but it said `ERROR! Download item xxxxxxxxxxx failed (Failure).Redirecting stderr to 'xxxxxxxxxxxx\steamcmd\logs\stderr.txt'`.

I wonder is it possible that Cities: Skylines workshop items will work in the future?

**Comment by shadoxxhd** [comment]
Cities: Skylines does not support anonymous downloading.

The next version of this program will support logging in with a steam account, but that account will probably need to own the game to download Cities: Skylines workshop items.

**Comment by shadoxxhd** [comment]
v0.5 implements login support.
