### ISSUE TITLE
Error parsing password

### ISSUE THREAD

**Issue by HairyMilkshakes** [shadoxxhd/steamworkshopdownloader#13]
Had the password in the .ini file but the .exe open and closes in a flash with the following error:

![EVARex4EM4](https://user-images.githubusercontent.com/13473043/175195397-d596078c-ffa5-462d-97b9-fa0b74e14bc0.png)
blanked out the text after "found:" since it's part of my password.

**Comment by shadoxxhd** [comment]
Should be fixed now, unless your password also has leading or trailing whitespaces ... which would probably break steamcmd login anyway.
