### ISSUE TITLE
downloader.py

### ISSUE THREAD

**Issue by DrawsHunter** [shadoxxhd/steamworkshopdownloader#16]
![image](https://user-images.githubusercontent.com/99562971/176428885-bcbe4f29-c511-4379-b6ea-2b6acbf14dce.png)
it's not downloader.exe but downloader.py i uninstalled python and it does the same thing

**Comment by shadoxxhd** [comment]
I'm not sure what your question is - downloader.exe is a standalone executable file created with pyinstaller, while downloader.py is the original python script, which requires a compatible python installation.
