### ISSUE TITLE
ERROR! Download item failed. (Timeout)

### ISSUE THREAD

**Issue by WitherSkell** [shadoxxhd/steamworkshopdownloader#19]
can't download addons from garry's mod.

![image](https://user-images.githubusercontent.com/51527151/178091116-407972a0-758b-4a61-a302-5c867f074465.png)
![image](https://user-images.githubusercontent.com/51527151/178091192-f1617559-ba5a-4ce7-ab09-4901d8b5bf30.png)

**Comment by RandDenner** [comment]
I tried with this URL, also got timeout failure with blank stderr.txt as well
https://steamcommunity.com/sharedfiles/filedetails/?id=1763518457&searchtext=decals+pack+4k

**Comment by shadoxxhd** [comment]
Can you download items from other games, or is this the only one with errors / only one you tried?

**Comment by WitherSkell** [comment]
only one i tried, cause, well, its the only one i need

tried to download  a map, went succesfully.
dunno why decals addon failed.
![Uploading image.png…]()

**Comment by WitherSkell** [comment]
the only one i tried yes.

tho a map worked! dunno why decals haven't worked :(

![image](https://user-images.githubusercontent.com/51527151/178151069-c31e10a2-6b31-4cd4-a9dd-fd267dbdff0e.png)

**Comment by shadoxxhd** [comment]
I got a timeout on the decal pack when not logged in, but when logged in (account owns gmod) it worked.
Please try the non-anonymous method (see readme for instructions) and check whether that works for you.

**Comment by shadoxxhd** [comment]
The "solution" seems to be that you need to be logged in for certain items from Garry's Mod. Doesn't seem to fixable from this end - if it's a problem for you, consider contacting the developers of Garry's Mod.
