### ISSUE TITLE
Exception in Tkinter callback & a question

### ISSUE THREAD

**Issue by Captchah** [shadoxxhd/steamworkshopdownloader#2]
So, I left my download to run about an hour ago, and when I returned it was stuck. I couldn't really figure out why until I decided to check the command prompt, where I found this:

```
Exception in Tkinter callback
Traceback (most recent call last):
  File "tkinter\__init__.py", line 1884, in __call__
  File "downloader.py", line 49, in download
  File "encodings\cp1253.py", line 23, in decode
UnicodeDecodeError: 'charmap' codec can't decode byte 0x88 in position 159: character maps to <undefined>

```
I happened to have SteamCMD already downloaded in my Downloads/steamcmd directory, so I just put downloader.exe in my Downloads directory, thinking it would work normally. It did until the exception. What is to blame?
<hr>
My question is about the changelog mention in Release 0.2, where it says:

> You can now also use workshop URLs instead of IDs, making copy&paste from your browser a bit faster.

Where exactly do you paste that URL? I tried pasting it in both App ID and Workshop ID separately and got this:
```
Exception in Tkinter callback
Traceback (most recent call last):
  File "tkinter\__init__.py", line 1884, in __call__
  File "downloader.py", line 29, in download
ValueError: invalid literal for int() with base 10: 'https://steamcommunity.com/sharedfiles/filedetails/?id=1527391789'
```
Pasting it in both did not seem to work either.
<hr>
Thank you for creating this! I hope you can add the ability to login with your account, sometime, even though I probably will stick to using SteamCMD on its own this is a great tool that helps automate the process, and makes downloading easier for many.

**Comment by shadoxxhd** [comment]
The first exception is SteamCMD printing a character code that isn't compatible with the default decoding of UTF-8.

The second problem is that the appID box still needs to be filled manually. Deducing the appID from the workshop URL is non-trivial, since I would have to actively parse the website (same for collection automation).

**Comment by shadoxxhd** [comment]
v0.3 should fix the first the decode crash.

**Comment by Captchah** [comment]
> v0.3 should fix the decode crash.

Can confirm it fixed it, thank you. 

> The second problem is that the appID box still needs to be filled manually.
Thanks for explaining about the URL, as well. It worked now too.
