### ISSUE TITLE
Can't run the downloader

### ISSUE THREAD

**Issue by ffsmyusernameistaken** [shadoxxhd/steamworkshopdownloader#22]
When I open it, I get an error "the program cannot be started because api-ms-win-core-path-l1-1-0.dll is missing". The translation is approximate because i'm using Windows in another language.

**Comment by shadoxxhd** [comment]
What OS are you using?

**Comment by ffsmyusernameistaken** [comment]
Windows 7.

**Comment by shadoxxhd** [comment]
python 3.9+ is not supported on windows 7. The best way to use this tool on your system is probably to install [python 3.8](https://www.python.org/downloads/release/python-3810/) and run the downloader.py file with python.exe.
