### ISSUE TITLE
Downloading a collection errors with <class 'TypeError'>expected str, bytes or os.PathLike object, not NoneType

### ISSUE THREAD

**Issue by Yagisan** [shadoxxhd/steamworkshopdownloader#25]
I am trying to download this collection [https://steamcommunity.com/sharedfiles/filedetails/?id=1163611154](https://steamcommunity.com/sharedfiles/filedetails/?id=1163611154) as a collection.

Unfortunately the process errors out with
`<class 'TypeError'>expected str, bytes or os.PathLike object, not NoneType`
![error](https://user-images.githubusercontent.com/172080/179401802-0cdbe155-acb5-4c6e-a08f-5ab8fb3c938b.png)

**Comment by shadoxxhd** [comment]
What's the content of your downloader.ini file?

**Comment by shadoxxhd** [comment]
Issue should be solved with the new release.
