### ISSUE TITLE
Unable to download items that are presumably year old

### ISSUE THREAD

**Issue by Emana202** [shadoxxhd/steamworkshopdownloader#3]
It seems that trying to download an item that was uploaded and last updated year ago or more, results in timeout error.
Tested in Garry's Mod Workshop, so idk if that happens with items in other workshops too

**Comment by shadoxxhd** [comment]
In general, the age of the item shouldn't have any effect on whether you can download it - I could download an old item from Garry's Mod (2345155546) just fine.

This seems to be either a bug in steamCMD/the workshop item itself, or a network issue on your side. Either way, there is nothing I can do to fix that.
