### ISSUE TITLE
Latest release crashes after a couple seconds of being open

### ISSUE THREAD

**Issue by Spaghet4Life** [shadoxxhd/steamworkshopdownloader#31]
The latest release (other releases work) opens a blank cmd window for a bit, then displays this error: 
`Traceback (most recent call last):
  File "downloader.py", line 4, in <module>
ModuleNotFoundError: No module named 'requests'
[15236] Failed to execute script 'downloader' due to unhandled exception!
`
for a split second before closing itself.
I am on Windows 10.

**Comment by UfaiX04** [comment]
I am encountering the same exact problem. Win 11
This should be a quick fix as afaik it could be a typo.

**Comment by shadoxxhd** [comment]
Fixed in v0.5.4.
