### ISSUE TITLE
Error failed to connect

### ISSUE THREAD

**Issue by ReDevils0** [shadoxxhd/steamworkshopdownloader#32]
Couldn't get workshop page for https://steamcommunity.com/sharedfiles/filedetails/?id=2842502659
<class 'requests.exceptions.ConnectionError'>
HTTPSConnectionPool(host='steamcommunity.com', port=443): Max retries exceeded with url: /sharedfiles/filedetails/?id=2842502659 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000029C715507C0>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))

**Comment by shadoxxhd** [comment]
Could you try it again? This sounds like a temporary problem with steams servers.

**Comment by ReDevils0** [comment]
i have try it again and it works now
