### ISSUE TITLE
ERROR! Download item 2813055911 failed (Failure).

### ISSUE THREAD

**Issue by Vibechecker202** [shadoxxhd/steamworkshopdownloader#33]
Whenever I try to download a worldbox mod this happens

**Comment by shadoxxhd** [comment]
Since worldbox is not on [this list](https://steamdb.info/sub/17906/apps/), you need to use an account owning the game to downloads mods for it (https://github.com/shadoxxhd/steamworkshopdownloader#non-anonymous-downloads).
