### ISSUE TITLE
Steamcmd opens and closes immediately

### ISSUE THREAD

**Issue by jumpthe11** [shadoxxhd/steamworkshopdownloader#35]
just creates bootstrap_log.txt and writes 
`
[2022-08-24 20:39:12] Startup - updater built Dec  2 2013 18:43:44`

inside in it.

**Comment by jumpthe11** [comment]
ok I found issue. downloader.exe MUST IN STEAM FOLDER

**Comment by jumpthe11** [comment]
now downloader.exe wants 2 factor login even I did on steamcmd

**Comment by jumpthe11** [comment]
![resim](https://user-images.githubusercontent.com/73638543/186598186-3e4e1b24-36b6-46e7-9de8-735fccc20824.png)

**Comment by shadoxxhd** [comment]
This seems to be a duplicate of the issue behind #21.
Are you using app-based 2FA?

**Comment by jumpthe11** [comment]
I guess yes. It has been long time since I used last time.

**Comment by shadoxxhd** [comment]
Closing as duplicate of #21 .
