### ISSUE TITLE
ERROR! Timeout

### ISSUE THREAD

**Issue by lurenyi4** [shadoxxhd/steamworkshopdownloader#36]
ERROR! Timeout downloading item XXXXXXXX   Redirecting stderr to 'D:\111\steamcmd\logs\stderr.txt'
[  0%] 姝ｅ湪妫鏌ュ彲鐢ㄦ洿鏂...
[----] 姝ｅ湪楠岃瘉瀹夎...

**Comment by shadoxxhd** [comment]
Probably some connection issue with steamcmd. Try again later, or try VPN/other inter etc connection if the issue persists.
There is nothing I can do, since steamcmd itself isn't open source.
