### ISSUE TITLE
Error download failed

### ISSUE THREAD

**Issue by Queenofdragons6** [shadoxxhd/steamworkshopdownloader#37]
I tried to download a mod and got an error message that said:
"ERROR! Download item 2836659083 failed (Failure).Message type 9806 wasn't declared, but we registered job CClientJobEnableOrDisableDownloads to handle it?"
I've been able to download mods for that game through the program before.

**Comment by Queenofdragons6** [comment]
Now it just says "ERROR! Download item [#] failed (Failure)."

**Comment by shadoxxhd** [comment]
Delete your steamcmd folder, then try again.
