### ISSUE TITLE
Windows 7 version

### ISSUE THREAD

**Issue by jjjr2062** [shadoxxhd/steamworkshopdownloader#38]
Hello.
Can you make a Windows 7 compatible version. The v0.5.4 version doesn't work because of a missing ridiculous 3kb 
api-ms-win-core-path-l1-1-0.dll !
Thanks.

**Comment by shadoxxhd** [comment]
You can find the required .dll here: https://github.com/nalexandru/api-ms-win-core-path-HACK

Adding support for older versions of python would mean making the code significantly less readable due to missing python features.
