### ISSUE TITLE
Error while downloading a file from the workshop

### ISSUE THREAD

**Issue by kRosZ1** [shadoxxhd/steamworkshopdownloader#40]
> ERROR! Download item 2517303243 failed (Failure).src\public\tier1\interface.h (264) : m_pModule
Anonymous doesn't work, this is the error msg from non anonymous. Any help?

**Comment by shadoxxhd** [comment]
You could delete the steamcmd directory and try again. If the issue persists, you should probably contact steam support, since the issue seems to be with the steamcmd executable, and I can't (legally as well as in terms of effort necessary) fix any bugs in there.
