### ISSUE TITLE
Download Item Failure

### ISSUE THREAD

**Issue by GangstaPichu** [shadoxxhd/steamworkshopdownloader#41]
I get this message every time I try. 

ERROR! Download item 2840824991 failed (Failure).src\public\tier1\interface.h (264) : m_pModule

At first, it just said failure, so I used an account login to see if that worked, and then the error got more detailed after that.

**Comment by GangstaPichu** [comment]
> 

I just tried that. Still says the same error.

**Comment by GangstaPichu** [comment]
If I have to contact steam like you told that one guy, where do I go for steamcmd since you can't play around with that?

**Comment by shadoxxhd** [comment]
The official page for steamcmd appears to be [this](https://developer.valvesoftware.com/wiki/SteamCMD). I have no experience contacting steam support.

**Comment by XemorDio** [comment]
Similar problem. Project Zomboid.

**Comment by XemorDio** [comment]
Corrected by deleting cache folders. Thanks for the tip. It works now.

**Comment by shadoxxhd** [comment]
Added cache wipe instructions to README.

**Comment by wa3k** [comment]
I have a similar problem but the error message is (Timeout)
