### ISSUE TITLE
I need help installing mods

### ISSUE THREAD

**Issue by SCPFOveerseerSCPF** [shadoxxhd/steamworkshopdownloader#45]
So I tried installing mods, I put the URL and clicked download and it's all good, but I start the game and nothing happens, I don't know if I'm supposed to do something else but it's not stated here on the site it just says to click download and that's it, my discord is C_706#9410 I'd greatly appreciate any help

**Comment by shadoxxhd** [comment]
This is just a downloader, not an installer. The installation process will be different for each individual game, as well as between distribution methods (steam, gog, other).

For details on how to install mods for a certain game, look into the games documentation or forums.

In most cases, this just entails moving the mod files to a certain folder, but for some games additional steps might be necessary (eg. generating descriptor files for Stellaris).
