### ISSUE TITLE
trying to download a BO3 custom map 

### ISSUE THREAD

**Issue by kemkera26** [shadoxxhd/steamworkshopdownloader#47]
i put the link in the app and after a few minutes it gives me this

...ERROR! Timeout downloading item 2672569148src\common\resourcecache.h (211) : m_unLockedItems == 0
src\common\pipes.cpp (885) : stalled cross-thread pipe.
src\clientdll\steamclient.cpp (901) : bufRet.TellPut() == sizeof(uint8)
src\common\asyncfileiohandler.cpp (249) : ~CAsyncFileIOHandlerImpl: failed to stop all threads
src\clientdll\contentupdatecontext.cpp (752) : m_uIOCurrentCacheSize == 0
src\clientdll\contentupdatecontext.cpp (752) : m_uIOCurrentCacheSize == 0
CWorkThreadPool::~CWorkThreadPool: work complete queue not empty, 1 items discarded.
src\common\resourcecache.h (215) : e.nLockCount == 0
src\common\resourcecache.h (163) : false
src\common\resourcecache.h (163) : false
src\common\resourcecache.h (163) : false
src\common\resourcecache.h (163) : false
src\common\resourcecache.h (163) : false
src\common\resourcecache.h (163) : false

what should i do?

**Comment by shadoxxhd** [comment]
You can try deleting the steamcmd folder and starting the download again.
If that doesn't help, your only real option is to contact steam support.
