### ISSUE TITLE
Two-factor code:FAILED (Account logon denied, need two-factor code)

### ISSUE THREAD

**Issue by Vic2077** [shadoxxhd/steamworkshopdownloader#48]
Done everything, steamcmd successfully logged in with 2fa, but the Downloader still can't download the file and returns this:

Steam Console Client (c) Valve Corporation - version 1694466999
Loading Steam API...OK
Logging in user 'REDACTED' to Steam Public...
Enter the current code from your Steam Guard Mobile Authenticator app
Two-factor code:FAILED (Account logon denied, need two-factor code)

It never asks for 2fa code, just returns FAILED immediately after I press "download".

**Comment by shadoxxhd** [comment]
better 2FA support was added in the latest release
