### ISSUE TITLE
bug: when entering a link, an error is written UnicodeEncodeError line 412

### ISSUE THREAD

**Issue by yo8z6gv** [shadoxxhd/steamworkshopdownloader#56]
To reproduce:
when entering a link, an error is written UnicodeEncodeError line 412
https://steamcommunity.com/sharedfiles/filedetails/?id=3238101432

`<class 'UnicodeEncodeError'>: 'charmap' codec can't encode characters in position 0-1: character maps to <undefined> (line 412)
`

**Comment by yo8z6gv** [comment]
and also tried to download a 100mb file, https://steamcommunity.com/sharedfiles/filedetails/?id=3246498384 the program went into "not responding" forever.

**Comment by shadoxxhd** [comment]
Fixed in latest release.
