### ISSUE TITLE
Bug: Collections not downloading fully

### ISSUE THREAD

**Issue by Random-Heretic** [shadoxxhd/steamworkshopdownloader#61]
Hello. First off all I have to say, I love your work.

However, I ran into a small issue. I tried to download a small collection of mods for Project Zomboid. About 40 mods in total. The issue I ran into is that the downloader starts and finishes the downloads normally but when I enter the downloads folder, I find only about 20 mod folders instead of the full collection.

Thanks in advance for any help.

**Comment by shadoxxhd** [comment]
Are you using the stable or experimental version?

Did you check the output of steamcmd whether there were any errors? The experimental branch should add failed items back to the download list and inform you of the problem; in 0.6.0 there should be a "failure" notice if steamcmd couldn't download some mod.

It's also possible that the `downloader.log` file contains interesting info...

**Comment by pavelbat3** [comment]
I have the similar problem, some mods just cant download for timeout, i've tried to download some of these mod directly from steam cmd, and also timeout

For example some of these mods
https://steamcommunity.com/sharedfiles/filedetails/?id=1118033221
https://steamcommunity.com/sharedfiles/filedetails/?id=769747007
https://steamcommunity.com/sharedfiles/filedetails/?id=1123150860
https://steamcommunity.com/sharedfiles/filedetails/?id=1563918075

Errors locks like 
Downloading [MOD NAME] ....ERROR (Timeout)

**Comment by shadoxxhd** [comment]
@pavel355 This sounds like an issue with steamcmd itself, and not this tool.

**Comment by pavelbat3** [comment]
> @pavel355 This sounds like an issue with steamcmd itself, and not this tool.

Yeah, it is, i think its something like access rights in steam, and its not tool issue
