### ISSUE TITLE
uninstall

### ISSUE THREAD

**Issue by Joackeur** [shadoxxhd/steamworkshopdownloader#66]
Hello, I can't find any mods folders in my stellaris directory to uninstall them. How do I do this?

**Comment by shadoxxhd** [comment]
This question isn't really related to this project, but I think mods should be in the `SteamLibrary/steamapps/workshop/content/281990/` directory, while there is also a `%USERPROFILE%\Documents\Paradox Interactive\Stellaris\mod` folder that may or may not contain descriptors for the mods.

The descriptors tell Stellaris where to look for the actual mod files; I'm not sure if they are necessary/automatically present for mods downloaded through the stream client.
