### ISSUE TITLE
Timeout errors

### ISSUE THREAD

**Issue by HairyMilkshakes** [shadoxxhd/steamworkshopdownloader#7]
Hi, getting the following timeout error, and nothing in the text file.

**Comment by shadoxxhd** [comment]
Since it is not in this list https://steamdb.info/sub/17906/apps/, it probably doesn't allow anonymous downloads.

**Comment by HairyMilkshakes** [comment]
Got it, thanks. And just saw your 0.5 alpha which supports login to bypass this issue, keep up the good work!
