### ISSUE TITLE
Stops responding when downloading collections

### ISSUE THREAD

**Issue by ElisPlayz** [shadoxxhd/steamworkshopdownloader#8]
The title said it all, however, I've noticed it does download some smaller collections, but if I put something like this to the test (https://steamcommunity.com/sharedfiles/filedetails/?id=2823277956) it straight bricks up and doesn't do anything. If you want to see this in action yourself, I can screenshare on Discord or something like that.

**Comment by shadoxxhd** [comment]
Fixed in v0.4.1.
